### ISSUE TITLE
autoplay not working

### ISSUE THREAD

**Issue by iamjohnbarker** [muxinc/hls-video-element#16] opened 2022-09-29 14:48 UTC
Loving the work done here!

I can't seem to get `autoplay` to work on my end though. Should this be added alongside `control`?

**Comment by dylanjha** [comment] 2022-09-29 15:46
@iamjohnbarker thanks for opening the issue. It seems to be working here:

https://codesandbox.io/s/hls-element-autoplay-ypsxuc?file=/index.html

```html
<hls-video
      controls
      autoplay
      muted
      src="https://stream.mux.com/DS00Spx1CV902MCtPj5WknGlR102V5HFkDe.m3u8"
    ></hls-video>
```

Anything I'm missing? All attributes that `<video>` has _should_ work the same for `<hls-video>`

**Comment by iamjohnbarker** [comment] 2022-09-29 17:10
Thanks for looking into it @dylanjha - Looks like it's because I used autoPlay instead I am using React and made an assumption. 

However even when written properly it is still inconsistent (which understandable is the browser).

I will say though that `muted` still doesn't work on my end.

Check out the bottom right module on our app here: https://app.dashmaster2k.com/s/XAA61LCY

**Comment by dylanjha** [comment] 2022-09-29 19:35
Thanks @iamjohnbarker that is... odd actually. I see the `muted` attribute on the underlying `<video>` element but the player is definitely not muted.

Not sure what's going on exactly, are you able to reproduce this on a codesandbox? That would make for easier debugging.

Just to be sure I tried changing `muted="true"` to `muted` (and same with `autoplay`)

![not-muted_2022-09-29_11-33-39](https://user-images.githubusercontent.com/764988/193125499-fcdb65dd-a820-4f6a-ba7f-aa630a120dd2.png)
![not-muted_2022-09-29_11-33-22](https://user-images.githubusercontent.com/764988/193125493-abce1ffe-d29c-4c0a-b3e5-5ee250b1a8f3.png)

Hmmm 🤔

**Comment by luwes** [comment] 2023-07-19 21:06
fixed in https://github.com/muxinc/hls-video-element/releases/tag/v0.0.5

**Closed by luwes** 2023-07-19 21:06 UTC
